name: ipdps26_vit

dependencies:
  - python=3.9
  - pip
  - pytorch=2.2
  - torchvision
  - pytorch-cuda=12.1
  - numpy
  - scipy
  - pandas
  - matplotlib
  - pyyaml
  - tqdm
  - networkx
  - pip:
      - flash-attn
      - gurobipy
